<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LoginUsername  AdminPassword  admin123U_4f763c</name>
   <tag></tag>
   <elementGuidId>9397cc11-d29e-4c1c-ac6f-c140d3c3a069</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-login-slot</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f1609115-080d-4237-bce2-69ed182bee1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-login-slot</value>
      <webElementGuid>e6db3a1a-a105-40bd-969e-a151c86000d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LoginUsername : AdminPassword : admin123UsernameRequiredPassword Login Forgot your password? OrangeHRM OS 5.1© 2005 - 2022 OrangeHRM, Inc. All rights reserved.</value>
      <webElementGuid>41a0ebdb-9254-471f-ba39-c0d4b6638b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;orangehrm-login-layout&quot;]/div[@class=&quot;orangehrm-login-layout-blob&quot;]/div[@class=&quot;orangehrm-login-container&quot;]/div[@class=&quot;orangehrm-login-slot-wrapper&quot;]/div[@class=&quot;orangehrm-login-slot&quot;]</value>
      <webElementGuid>9f06d50c-dd3b-4717-a14b-8849f9db7766</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div[2]</value>
      <webElementGuid>29895523-bd65-4e35-b89b-ac623e4a8568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]</value>
      <webElementGuid>aeb95473-4d8e-45b5-9001-ad6c3932be18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LoginUsername : AdminPassword : admin123UsernameRequiredPassword Login Forgot your password? OrangeHRM OS 5.1© 2005 - 2022 OrangeHRM, Inc. All rights reserved.' or . = 'LoginUsername : AdminPassword : admin123UsernameRequiredPassword Login Forgot your password? OrangeHRM OS 5.1© 2005 - 2022 OrangeHRM, Inc. All rights reserved.')]</value>
      <webElementGuid>824d3d13-0019-43d4-8ecf-519bea9f46b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
